version: 2

builds:
  - skip: true

release:
  # What to do with the release notes in case there the release already exists.
  mode: replace

announce:
  # Requires TELEGRAM_TOKEN env var
  telegram:
    enabled: true
    chat_id: -1002950691807
    message_template: '[{{ mdv2escape .ProjectName }} {{ mdv2escape .Tag }}]({{ mdv2escape .ReleaseURL }}) is out{{ mdv2escape "!" }}'

